//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturanteMVC.API
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ListadoComprobantesRequest", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API")]
    public partial class ListadoComprobantesRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private FacturanteMVC.API.DTOs.Autenticacion AutenticacionField;

        private string CUITField;

        private System.DateTime FechaDesdeField;

        private System.DateTime FechaHastaField;

        private System.Nullable<int> IdComprobanteField;

        private System.Nullable<int> NroPaginaField;

        private string TipoComprobanteField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteMVC.API.DTOs.Autenticacion Autenticacion
        {
            get
            {
                return this.AutenticacionField;
            }
            set
            {
                this.AutenticacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUIT
        {
            get
            {
                return this.CUITField;
            }
            set
            {
                this.CUITField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDesde
        {
            get
            {
                return this.FechaDesdeField;
            }
            set
            {
                this.FechaDesdeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHasta
        {
            get
            {
                return this.FechaHastaField;
            }
            set
            {
                this.FechaHastaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdComprobante
        {
            get
            {
                return this.IdComprobanteField;
            }
            set
            {
                this.IdComprobanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NroPagina
        {
            get
            {
                return this.NroPaginaField;
            }
            set
            {
                this.NroPaginaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoComprobante
        {
            get
            {
                return this.TipoComprobanteField;
            }
            set
            {
                this.TipoComprobanteField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ResponseBase", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FacturanteMVC.API.CrearComprobanteResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FacturanteMVC.API.CrearEmpresaResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FacturanteMVC.API.ListadoComprobantesResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private FacturanteModel.ConstantesCodigoRespuesta CodigoField;

        private FacturanteModel.ConstantesEstadoRespuesta EstadoField;

        private string MensajeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteModel.ConstantesCodigoRespuesta Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteModel.ConstantesEstadoRespuesta Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CrearComprobanteResponse", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API")]
    public partial class CrearComprobanteResponse : FacturanteMVC.API.ResponseBase
    {

        private System.Nullable<int> IdComprobanteField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdComprobante
        {
            get
            {
                return this.IdComprobanteField;
            }
            set
            {
                this.IdComprobanteField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CrearEmpresaResponse", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API")]
    public partial class CrearEmpresaResponse : FacturanteMVC.API.ResponseBase
    {

        private int IdEmpresaField;

        private FacturanteMVC.API.DTOs.Error[] ListadoErroresField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpresa
        {
            get
            {
                return this.IdEmpresaField;
            }
            set
            {
                this.IdEmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteMVC.API.DTOs.Error[] ListadoErrores
        {
            get
            {
                return this.ListadoErroresField;
            }
            set
            {
                this.ListadoErroresField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ListadoComprobantesResponse", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API")]
    public partial class ListadoComprobantesResponse : FacturanteMVC.API.ResponseBase
    {

        private FacturanteMVC.API.DTOs.Comprobante[] ListadoComprobantesField;

        private int PaginaActualField;

        private int TotalComprobantesField;

        private int TotalPaginasField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteMVC.API.DTOs.Comprobante[] ListadoComprobantes
        {
            get
            {
                return this.ListadoComprobantesField;
            }
            set
            {
                this.ListadoComprobantesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaginaActual
        {
            get
            {
                return this.PaginaActualField;
            }
            set
            {
                this.PaginaActualField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalComprobantes
        {
            get
            {
                return this.TotalComprobantesField;
            }
            set
            {
                this.TotalComprobantesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPaginas
        {
            get
            {
                return this.TotalPaginasField;
            }
            set
            {
                this.TotalPaginasField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CrearComprobanteRequest", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API")]
    public partial class CrearComprobanteRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private FacturanteMVC.API.DTOs.Autenticacion AutenticacionField;

        private FacturanteMVC.API.DTOs.Cliente ClienteField;

        private FacturanteMVC.API.DTOs.ComprobanteEncabezado EncabezadoField;

        private FacturanteMVC.API.DTOs.ComprobanteItem[] ItemsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteMVC.API.DTOs.Autenticacion Autenticacion
        {
            get
            {
                return this.AutenticacionField;
            }
            set
            {
                this.AutenticacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteMVC.API.DTOs.Cliente Cliente
        {
            get
            {
                return this.ClienteField;
            }
            set
            {
                this.ClienteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteMVC.API.DTOs.ComprobanteEncabezado Encabezado
        {
            get
            {
                return this.EncabezadoField;
            }
            set
            {
                this.EncabezadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteMVC.API.DTOs.ComprobanteItem[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CrearEmpresaRequest", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API")]
    public partial class CrearEmpresaRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private FacturanteMVC.API.DTOs.AutenticacionReseller AutenticacionField;

        private FacturanteMVC.API.DTOs.Empresa EmpresaField;

        private FacturanteMVC.API.DTOs.Sucursal SucursalField;

        private FacturanteMVC.API.DTOs.Usuario UsuarioField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteMVC.API.DTOs.AutenticacionReseller Autenticacion
        {
            get
            {
                return this.AutenticacionField;
            }
            set
            {
                this.AutenticacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteMVC.API.DTOs.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteMVC.API.DTOs.Sucursal Sucursal
        {
            get
            {
                return this.SucursalField;
            }
            set
            {
                this.SucursalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteMVC.API.DTOs.Usuario Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ReenviarComprobanteRequest", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API")]
    public partial class ReenviarComprobanteRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private FacturanteMVC.API.DTOs.Autenticacion AutenticacionField;

        private string DireccionesField;

        private int IdComprobanteField;

        private bool NoIncluirCCField;

        private bool NoIncluirMailFacturacionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteMVC.API.DTOs.Autenticacion Autenticacion
        {
            get
            {
                return this.AutenticacionField;
            }
            set
            {
                this.AutenticacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direcciones
        {
            get
            {
                return this.DireccionesField;
            }
            set
            {
                this.DireccionesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdComprobante
        {
            get
            {
                return this.IdComprobanteField;
            }
            set
            {
                this.IdComprobanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NoIncluirCC
        {
            get
            {
                return this.NoIncluirCCField;
            }
            set
            {
                this.NoIncluirCCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NoIncluirMailFacturacion
        {
            get
            {
                return this.NoIncluirMailFacturacionField;
            }
            set
            {
                this.NoIncluirMailFacturacionField = value;
            }
        }
    }
}
namespace FacturanteMVC.API.DTOs
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Autenticacion", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API.DTOs")]
    public partial class Autenticacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int EmpresaField;

        private string HashField;

        private string UsuarioField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash
        {
            get
            {
                return this.HashField;
            }
            set
            {
                this.HashField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Comprobante", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API.DTOs")]
    public partial class Comprobante : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int BienesField;

        private System.Nullable<decimal> CAEField;

        private FacturanteMVC.API.DTOs.Cliente ClienteField;

        private string CodigoPagoElectronicoField;

        private int CondicionVentaField;

        private bool EnviarComprobanteField;

        private int EstadoComprobanteField;

        private int EstadoConfirmadoField;

        private System.DateTime FechaHoraField;

        private System.Nullable<System.DateTime> FechaHoraCAEField;

        private System.Nullable<System.DateTime> FechaServDesdeField;

        private System.Nullable<System.DateTime> FechaServHastaField;

        private System.Nullable<System.DateTime> FechaVencimientoCaeField;

        private System.Nullable<System.DateTime> FechaVtoPagoField;

        private System.Nullable<decimal> IVA1Field;

        private System.Nullable<decimal> IVA2Field;

        private System.Nullable<decimal> IVA3Field;

        private int IdComprobanteField;

        private System.Nullable<decimal> ImporteImpuestosInternosField;

        private System.Nullable<decimal> ImportePercepcionesMunicField;

        private short IntentosEnvioMailField;

        private FacturanteMVC.API.DTOs.ComprobanteItem[] ItemsField;

        private string MensajeAFIPField;

        private int MonedaField;

        private System.Nullable<int> NumeroField;

        private string ObservacionesField;

        private string OrdenCompraField;

        private System.Nullable<decimal> PercepcionIIBBField;

        private System.Nullable<decimal> PercepcionIVAField;

        private string PrefijoField;

        private string RemitoField;

        private System.Nullable<decimal> SubTotalField;

        private System.Nullable<decimal> SubTotalExcentoField;

        private System.Nullable<decimal> SubtotalNoAlcanzadoField;

        private string TipoComprobanteField;

        private decimal TipoDeCambioField;

        private System.Nullable<decimal> TotalField;

        private System.Nullable<decimal> TotalConDescuentoField;

        private System.Nullable<decimal> TotalNetoField;

        private string URLPDFField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bienes
        {
            get
            {
                return this.BienesField;
            }
            set
            {
                this.BienesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CAE
        {
            get
            {
                return this.CAEField;
            }
            set
            {
                this.CAEField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteMVC.API.DTOs.Cliente Cliente
        {
            get
            {
                return this.ClienteField;
            }
            set
            {
                this.ClienteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPagoElectronico
        {
            get
            {
                return this.CodigoPagoElectronicoField;
            }
            set
            {
                this.CodigoPagoElectronicoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CondicionVenta
        {
            get
            {
                return this.CondicionVentaField;
            }
            set
            {
                this.CondicionVentaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnviarComprobante
        {
            get
            {
                return this.EnviarComprobanteField;
            }
            set
            {
                this.EnviarComprobanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoComprobante
        {
            get
            {
                return this.EstadoComprobanteField;
            }
            set
            {
                this.EstadoComprobanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoConfirmado
        {
            get
            {
                return this.EstadoConfirmadoField;
            }
            set
            {
                this.EstadoConfirmadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHora
        {
            get
            {
                return this.FechaHoraField;
            }
            set
            {
                this.FechaHoraField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaHoraCAE
        {
            get
            {
                return this.FechaHoraCAEField;
            }
            set
            {
                this.FechaHoraCAEField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaServDesde
        {
            get
            {
                return this.FechaServDesdeField;
            }
            set
            {
                this.FechaServDesdeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaServHasta
        {
            get
            {
                return this.FechaServHastaField;
            }
            set
            {
                this.FechaServHastaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaVencimientoCae
        {
            get
            {
                return this.FechaVencimientoCaeField;
            }
            set
            {
                this.FechaVencimientoCaeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaVtoPago
        {
            get
            {
                return this.FechaVtoPagoField;
            }
            set
            {
                this.FechaVtoPagoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> IVA1
        {
            get
            {
                return this.IVA1Field;
            }
            set
            {
                this.IVA1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> IVA2
        {
            get
            {
                return this.IVA2Field;
            }
            set
            {
                this.IVA2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> IVA3
        {
            get
            {
                return this.IVA3Field;
            }
            set
            {
                this.IVA3Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdComprobante
        {
            get
            {
                return this.IdComprobanteField;
            }
            set
            {
                this.IdComprobanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ImporteImpuestosInternos
        {
            get
            {
                return this.ImporteImpuestosInternosField;
            }
            set
            {
                this.ImporteImpuestosInternosField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ImportePercepcionesMunic
        {
            get
            {
                return this.ImportePercepcionesMunicField;
            }
            set
            {
                this.ImportePercepcionesMunicField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IntentosEnvioMail
        {
            get
            {
                return this.IntentosEnvioMailField;
            }
            set
            {
                this.IntentosEnvioMailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public FacturanteMVC.API.DTOs.ComprobanteItem[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeAFIP
        {
            get
            {
                return this.MensajeAFIPField;
            }
            set
            {
                this.MensajeAFIPField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones
        {
            get
            {
                return this.ObservacionesField;
            }
            set
            {
                this.ObservacionesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrdenCompra
        {
            get
            {
                return this.OrdenCompraField;
            }
            set
            {
                this.OrdenCompraField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PercepcionIIBB
        {
            get
            {
                return this.PercepcionIIBBField;
            }
            set
            {
                this.PercepcionIIBBField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PercepcionIVA
        {
            get
            {
                return this.PercepcionIVAField;
            }
            set
            {
                this.PercepcionIVAField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo
        {
            get
            {
                return this.PrefijoField;
            }
            set
            {
                this.PrefijoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remito
        {
            get
            {
                return this.RemitoField;
            }
            set
            {
                this.RemitoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SubTotal
        {
            get
            {
                return this.SubTotalField;
            }
            set
            {
                this.SubTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SubTotalExcento
        {
            get
            {
                return this.SubTotalExcentoField;
            }
            set
            {
                this.SubTotalExcentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SubtotalNoAlcanzado
        {
            get
            {
                return this.SubtotalNoAlcanzadoField;
            }
            set
            {
                this.SubtotalNoAlcanzadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoComprobante
        {
            get
            {
                return this.TipoComprobanteField;
            }
            set
            {
                this.TipoComprobanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TipoDeCambio
        {
            get
            {
                return this.TipoDeCambioField;
            }
            set
            {
                this.TipoDeCambioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalConDescuento
        {
            get
            {
                return this.TotalConDescuentoField;
            }
            set
            {
                this.TotalConDescuentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalNeto
        {
            get
            {
                return this.TotalNetoField;
            }
            set
            {
                this.TotalNetoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URLPDF
        {
            get
            {
                return this.URLPDFField;
            }
            set
            {
                this.URLPDFField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Error", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API.DTOs")]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CampoField;

        private string DetalleField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo
        {
            get
            {
                return this.CampoField;
            }
            set
            {
                this.CampoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalle
        {
            get
            {
                return this.DetalleField;
            }
            set
            {
                this.DetalleField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Cliente", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API.DTOs")]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodigoPostalField;

        private System.Nullable<int> CondicionPagoField;

        private string ContactoField;

        private string DireccionFiscalField;

        private bool EnviarComprobanteField;

        private string LocalidadField;

        private string MailContactoField;

        private string MailFacturacionField;

        private string NroDocumentoField;

        private bool PercibeIIBBField;

        private bool PercibeIVAField;

        private string ProvinciaField;

        private string RazonSocialField;

        private string TelefonoField;

        private int TipoDocumentoField;

        private System.Nullable<int> TratamientoImpositivoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal
        {
            get
            {
                return this.CodigoPostalField;
            }
            set
            {
                this.CodigoPostalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CondicionPago
        {
            get
            {
                return this.CondicionPagoField;
            }
            set
            {
                this.CondicionPagoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacto
        {
            get
            {
                return this.ContactoField;
            }
            set
            {
                this.ContactoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionFiscal
        {
            get
            {
                return this.DireccionFiscalField;
            }
            set
            {
                this.DireccionFiscalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnviarComprobante
        {
            get
            {
                return this.EnviarComprobanteField;
            }
            set
            {
                this.EnviarComprobanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidad
        {
            get
            {
                return this.LocalidadField;
            }
            set
            {
                this.LocalidadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailContacto
        {
            get
            {
                return this.MailContactoField;
            }
            set
            {
                this.MailContactoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailFacturacion
        {
            get
            {
                return this.MailFacturacionField;
            }
            set
            {
                this.MailFacturacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroDocumento
        {
            get
            {
                return this.NroDocumentoField;
            }
            set
            {
                this.NroDocumentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PercibeIIBB
        {
            get
            {
                return this.PercibeIIBBField;
            }
            set
            {
                this.PercibeIIBBField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PercibeIVA
        {
            get
            {
                return this.PercibeIVAField;
            }
            set
            {
                this.PercibeIVAField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this.RazonSocialField;
            }
            set
            {
                this.RazonSocialField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDocumento
        {
            get
            {
                return this.TipoDocumentoField;
            }
            set
            {
                this.TipoDocumentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TratamientoImpositivo
        {
            get
            {
                return this.TratamientoImpositivoField;
            }
            set
            {
                this.TratamientoImpositivoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ComprobanteItem", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API.DTOs")]
    public partial class ComprobanteItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Nullable<decimal> BonificacionField;

        private decimal CantidadField;

        private string CodigoField;

        private string DetalleField;

        private bool GravadoField;

        private decimal IVAField;

        private decimal PrecioUnitarioField;

        private decimal TotalField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Bonificacion
        {
            get
            {
                return this.BonificacionField;
            }
            set
            {
                this.BonificacionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalle
        {
            get
            {
                return this.DetalleField;
            }
            set
            {
                this.DetalleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Gravado
        {
            get
            {
                return this.GravadoField;
            }
            set
            {
                this.GravadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IVA
        {
            get
            {
                return this.IVAField;
            }
            set
            {
                this.IVAField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioUnitario
        {
            get
            {
                return this.PrecioUnitarioField;
            }
            set
            {
                this.PrecioUnitarioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ComprobanteEncabezado", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API.DTOs")]
    public partial class ComprobanteEncabezado : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int BienesField;

        private string CodigoPagoElectronicoField;

        private int CondicionVentaField;

        private bool EnviarComprobanteField;

        private System.DateTime FechaHoraField;

        private System.Nullable<System.DateTime> FechaServDesdeField;

        private System.Nullable<System.DateTime> FechaServHastaField;

        private System.Nullable<System.DateTime> FechaVtoPagoField;

        private System.Nullable<decimal> ImporteImpuestosInternosField;

        private System.Nullable<decimal> ImportePercepcionesMunicField;

        private int MonedaField;

        private string ObservacionesField;

        private string OrdenCompraField;

        private System.Nullable<decimal> PercepcionIIBBField;

        private System.Nullable<decimal> PercepcionIVAField;

        private decimal PorcentajeIIBBField;

        private string PrefijoField;

        private string RemitoField;

        private System.Nullable<decimal> SubTotalField;

        private System.Nullable<decimal> SubTotalExcentoField;

        private System.Nullable<decimal> SubTotalNoAlcanzadoField;

        private string TipoComprobanteField;

        private decimal TipoDeCambioField;

        private System.Nullable<decimal> TotalField;

        private System.Nullable<decimal> TotalConDescuentoField;

        private System.Nullable<decimal> TotalNetoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bienes
        {
            get
            {
                return this.BienesField;
            }
            set
            {
                this.BienesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPagoElectronico
        {
            get
            {
                return this.CodigoPagoElectronicoField;
            }
            set
            {
                this.CodigoPagoElectronicoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CondicionVenta
        {
            get
            {
                return this.CondicionVentaField;
            }
            set
            {
                this.CondicionVentaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnviarComprobante
        {
            get
            {
                return this.EnviarComprobanteField;
            }
            set
            {
                this.EnviarComprobanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHora
        {
            get
            {
                return this.FechaHoraField;
            }
            set
            {
                this.FechaHoraField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaServDesde
        {
            get
            {
                return this.FechaServDesdeField;
            }
            set
            {
                this.FechaServDesdeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaServHasta
        {
            get
            {
                return this.FechaServHastaField;
            }
            set
            {
                this.FechaServHastaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaVtoPago
        {
            get
            {
                return this.FechaVtoPagoField;
            }
            set
            {
                this.FechaVtoPagoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ImporteImpuestosInternos
        {
            get
            {
                return this.ImporteImpuestosInternosField;
            }
            set
            {
                this.ImporteImpuestosInternosField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ImportePercepcionesMunic
        {
            get
            {
                return this.ImportePercepcionesMunicField;
            }
            set
            {
                this.ImportePercepcionesMunicField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones
        {
            get
            {
                return this.ObservacionesField;
            }
            set
            {
                this.ObservacionesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrdenCompra
        {
            get
            {
                return this.OrdenCompraField;
            }
            set
            {
                this.OrdenCompraField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PercepcionIIBB
        {
            get
            {
                return this.PercepcionIIBBField;
            }
            set
            {
                this.PercepcionIIBBField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PercepcionIVA
        {
            get
            {
                return this.PercepcionIVAField;
            }
            set
            {
                this.PercepcionIVAField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PorcentajeIIBB
        {
            get
            {
                return this.PorcentajeIIBBField;
            }
            set
            {
                this.PorcentajeIIBBField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo
        {
            get
            {
                return this.PrefijoField;
            }
            set
            {
                this.PrefijoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remito
        {
            get
            {
                return this.RemitoField;
            }
            set
            {
                this.RemitoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SubTotal
        {
            get
            {
                return this.SubTotalField;
            }
            set
            {
                this.SubTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SubTotalExcento
        {
            get
            {
                return this.SubTotalExcentoField;
            }
            set
            {
                this.SubTotalExcentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SubTotalNoAlcanzado
        {
            get
            {
                return this.SubTotalNoAlcanzadoField;
            }
            set
            {
                this.SubTotalNoAlcanzadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoComprobante
        {
            get
            {
                return this.TipoComprobanteField;
            }
            set
            {
                this.TipoComprobanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TipoDeCambio
        {
            get
            {
                return this.TipoDeCambioField;
            }
            set
            {
                this.TipoDeCambioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalConDescuento
        {
            get
            {
                return this.TotalConDescuentoField;
            }
            set
            {
                this.TotalConDescuentoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalNeto
        {
            get
            {
                return this.TotalNetoField;
            }
            set
            {
                this.TotalNetoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AutenticacionReseller", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API.DTOs")]
    public partial class AutenticacionReseller : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string HashField;

        private int ResellerField;

        private string UsuarioField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash
        {
            get
            {
                return this.HashField;
            }
            set
            {
                this.HashField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Reseller
        {
            get
            {
                return this.ResellerField;
            }
            set
            {
                this.ResellerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Empresa", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API.DTOs")]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AlicuotaGeneralField;

        private System.Nullable<bool> AlicuotaIIBBTablaField;

        private string CUITField;

        private string CodigoPostalField;

        private int CondicionPagoField;

        private string DineroMail_EmailField;

        private string DineroMail_NumeroCuentaField;

        private string DineroMail_PINField;

        private string DireccionFiscalField;

        private bool EliminaComprobantesField;

        private string FromEmailComprobanteField;

        private string IIBBField;

        private string IVADefaultField;

        private System.Nullable<decimal> ImporteMinimoPercepcionIIBBField;

        private System.DateTime InicioActividadesField;

        private string LocalidadField;

        private string MailField;

        private string MailContadorField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_AmexField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_ArgencardField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_BapropagoField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_CabalField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_CobroField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_DineroMailField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_ItalcredField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_MasterField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_NaranjaField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_PagoFacilField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_RapipagoField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_RipsaField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_TShoppingField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_TransferenciaBancariaField;

        private System.Nullable<bool> MediosPagoDineroMail_AR_VisaField;

        private System.Nullable<bool> MediosPagoMercadoPago_AmexField;

        private System.Nullable<bool> MediosPagoMercadoPago_ArgencardField;

        private System.Nullable<bool> MediosPagoMercadoPago_BanelcoField;

        private System.Nullable<bool> MediosPagoMercadoPago_BapropagosField;

        private System.Nullable<bool> MediosPagoMercadoPago_CabalField;

        private System.Nullable<bool> MediosPagoMercadoPago_CencosudField;

        private System.Nullable<bool> MediosPagoMercadoPago_MasterField;

        private System.Nullable<bool> MediosPagoMercadoPago_NativaField;

        private System.Nullable<bool> MediosPagoMercadoPago_PagofacilField;

        private System.Nullable<bool> MediosPagoMercadoPago_RapipagoField;

        private System.Nullable<bool> MediosPagoMercadoPago_RedlinkField;

        private System.Nullable<bool> MediosPagoMercadoPago_TnaranjaField;

        private System.Nullable<bool> MediosPagoMercadoPago_TshoppingField;

        private System.Nullable<bool> MediosPagoMercadoPago_VisaField;

        private string MercadoPago_ClientIdField;

        private string MercadoPago_ClientSecretField;

        private bool PercibeIIBBField;

        private bool PercibeIVAField;

        private string ProvinciaField;

        private string RazonSocialField;

        private string TelefonoField;

        private int TratamientoImpositivoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlicuotaGeneral
        {
            get
            {
                return this.AlicuotaGeneralField;
            }
            set
            {
                this.AlicuotaGeneralField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> AlicuotaIIBBTabla
        {
            get
            {
                return this.AlicuotaIIBBTablaField;
            }
            set
            {
                this.AlicuotaIIBBTablaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUIT
        {
            get
            {
                return this.CUITField;
            }
            set
            {
                this.CUITField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal
        {
            get
            {
                return this.CodigoPostalField;
            }
            set
            {
                this.CodigoPostalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CondicionPago
        {
            get
            {
                return this.CondicionPagoField;
            }
            set
            {
                this.CondicionPagoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DineroMail_Email
        {
            get
            {
                return this.DineroMail_EmailField;
            }
            set
            {
                this.DineroMail_EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DineroMail_NumeroCuenta
        {
            get
            {
                return this.DineroMail_NumeroCuentaField;
            }
            set
            {
                this.DineroMail_NumeroCuentaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DineroMail_PIN
        {
            get
            {
                return this.DineroMail_PINField;
            }
            set
            {
                this.DineroMail_PINField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionFiscal
        {
            get
            {
                return this.DireccionFiscalField;
            }
            set
            {
                this.DireccionFiscalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EliminaComprobantes
        {
            get
            {
                return this.EliminaComprobantesField;
            }
            set
            {
                this.EliminaComprobantesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromEmailComprobante
        {
            get
            {
                return this.FromEmailComprobanteField;
            }
            set
            {
                this.FromEmailComprobanteField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IIBB
        {
            get
            {
                return this.IIBBField;
            }
            set
            {
                this.IIBBField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IVADefault
        {
            get
            {
                return this.IVADefaultField;
            }
            set
            {
                this.IVADefaultField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ImporteMinimoPercepcionIIBB
        {
            get
            {
                return this.ImporteMinimoPercepcionIIBBField;
            }
            set
            {
                this.ImporteMinimoPercepcionIIBBField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InicioActividades
        {
            get
            {
                return this.InicioActividadesField;
            }
            set
            {
                this.InicioActividadesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidad
        {
            get
            {
                return this.LocalidadField;
            }
            set
            {
                this.LocalidadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail
        {
            get
            {
                return this.MailField;
            }
            set
            {
                this.MailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailContador
        {
            get
            {
                return this.MailContadorField;
            }
            set
            {
                this.MailContadorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_Amex
        {
            get
            {
                return this.MediosPagoDineroMail_AR_AmexField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_AmexField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_Argencard
        {
            get
            {
                return this.MediosPagoDineroMail_AR_ArgencardField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_ArgencardField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_Bapropago
        {
            get
            {
                return this.MediosPagoDineroMail_AR_BapropagoField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_BapropagoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_Cabal
        {
            get
            {
                return this.MediosPagoDineroMail_AR_CabalField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_CabalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_Cobro
        {
            get
            {
                return this.MediosPagoDineroMail_AR_CobroField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_CobroField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_DineroMail
        {
            get
            {
                return this.MediosPagoDineroMail_AR_DineroMailField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_DineroMailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_Italcred
        {
            get
            {
                return this.MediosPagoDineroMail_AR_ItalcredField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_ItalcredField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_Master
        {
            get
            {
                return this.MediosPagoDineroMail_AR_MasterField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_MasterField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_Naranja
        {
            get
            {
                return this.MediosPagoDineroMail_AR_NaranjaField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_NaranjaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_PagoFacil
        {
            get
            {
                return this.MediosPagoDineroMail_AR_PagoFacilField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_PagoFacilField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_Rapipago
        {
            get
            {
                return this.MediosPagoDineroMail_AR_RapipagoField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_RapipagoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_Ripsa
        {
            get
            {
                return this.MediosPagoDineroMail_AR_RipsaField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_RipsaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_TShopping
        {
            get
            {
                return this.MediosPagoDineroMail_AR_TShoppingField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_TShoppingField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_TransferenciaBancaria
        {
            get
            {
                return this.MediosPagoDineroMail_AR_TransferenciaBancariaField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_TransferenciaBancariaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoDineroMail_AR_Visa
        {
            get
            {
                return this.MediosPagoDineroMail_AR_VisaField;
            }
            set
            {
                this.MediosPagoDineroMail_AR_VisaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoMercadoPago_Amex
        {
            get
            {
                return this.MediosPagoMercadoPago_AmexField;
            }
            set
            {
                this.MediosPagoMercadoPago_AmexField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoMercadoPago_Argencard
        {
            get
            {
                return this.MediosPagoMercadoPago_ArgencardField;
            }
            set
            {
                this.MediosPagoMercadoPago_ArgencardField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoMercadoPago_Banelco
        {
            get
            {
                return this.MediosPagoMercadoPago_BanelcoField;
            }
            set
            {
                this.MediosPagoMercadoPago_BanelcoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoMercadoPago_Bapropagos
        {
            get
            {
                return this.MediosPagoMercadoPago_BapropagosField;
            }
            set
            {
                this.MediosPagoMercadoPago_BapropagosField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoMercadoPago_Cabal
        {
            get
            {
                return this.MediosPagoMercadoPago_CabalField;
            }
            set
            {
                this.MediosPagoMercadoPago_CabalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoMercadoPago_Cencosud
        {
            get
            {
                return this.MediosPagoMercadoPago_CencosudField;
            }
            set
            {
                this.MediosPagoMercadoPago_CencosudField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoMercadoPago_Master
        {
            get
            {
                return this.MediosPagoMercadoPago_MasterField;
            }
            set
            {
                this.MediosPagoMercadoPago_MasterField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoMercadoPago_Nativa
        {
            get
            {
                return this.MediosPagoMercadoPago_NativaField;
            }
            set
            {
                this.MediosPagoMercadoPago_NativaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoMercadoPago_Pagofacil
        {
            get
            {
                return this.MediosPagoMercadoPago_PagofacilField;
            }
            set
            {
                this.MediosPagoMercadoPago_PagofacilField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoMercadoPago_Rapipago
        {
            get
            {
                return this.MediosPagoMercadoPago_RapipagoField;
            }
            set
            {
                this.MediosPagoMercadoPago_RapipagoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoMercadoPago_Redlink
        {
            get
            {
                return this.MediosPagoMercadoPago_RedlinkField;
            }
            set
            {
                this.MediosPagoMercadoPago_RedlinkField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoMercadoPago_Tnaranja
        {
            get
            {
                return this.MediosPagoMercadoPago_TnaranjaField;
            }
            set
            {
                this.MediosPagoMercadoPago_TnaranjaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoMercadoPago_Tshopping
        {
            get
            {
                return this.MediosPagoMercadoPago_TshoppingField;
            }
            set
            {
                this.MediosPagoMercadoPago_TshoppingField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MediosPagoMercadoPago_Visa
        {
            get
            {
                return this.MediosPagoMercadoPago_VisaField;
            }
            set
            {
                this.MediosPagoMercadoPago_VisaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MercadoPago_ClientId
        {
            get
            {
                return this.MercadoPago_ClientIdField;
            }
            set
            {
                this.MercadoPago_ClientIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MercadoPago_ClientSecret
        {
            get
            {
                return this.MercadoPago_ClientSecretField;
            }
            set
            {
                this.MercadoPago_ClientSecretField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PercibeIIBB
        {
            get
            {
                return this.PercibeIIBBField;
            }
            set
            {
                this.PercibeIIBBField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PercibeIVA
        {
            get
            {
                return this.PercibeIVAField;
            }
            set
            {
                this.PercibeIVAField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this.RazonSocialField;
            }
            set
            {
                this.RazonSocialField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TratamientoImpositivo
        {
            get
            {
                return this.TratamientoImpositivoField;
            }
            set
            {
                this.TratamientoImpositivoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Sucursal", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API.DTOs")]
    public partial class Sucursal : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AsuntoPersonalizadoField;

        private string CodigoPostalField;

        private string DireccionField;

        private string LocalidadField;

        private string MailField;

        private string MensajePersonalizadoField;

        private string NombrePuntoVentaField;

        private string PrefijoField;

        private string ProvinciaField;

        private string TelefonoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AsuntoPersonalizado
        {
            get
            {
                return this.AsuntoPersonalizadoField;
            }
            set
            {
                this.AsuntoPersonalizadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal
        {
            get
            {
                return this.CodigoPostalField;
            }
            set
            {
                this.CodigoPostalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidad
        {
            get
            {
                return this.LocalidadField;
            }
            set
            {
                this.LocalidadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail
        {
            get
            {
                return this.MailField;
            }
            set
            {
                this.MailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajePersonalizado
        {
            get
            {
                return this.MensajePersonalizadoField;
            }
            set
            {
                this.MensajePersonalizadoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePuntoVenta
        {
            get
            {
                return this.NombrePuntoVentaField;
            }
            set
            {
                this.NombrePuntoVentaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefijo
        {
            get
            {
                return this.PrefijoField;
            }
            set
            {
                this.PrefijoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Usuario", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteMVC.API.DTOs")]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ApellidoField;

        private string CelularField;

        private string ContraseniaField;

        private string MailField;

        private string NombreField;

        private string NombreUsuarioField;

        private string TelefonoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido
        {
            get
            {
                return this.ApellidoField;
            }
            set
            {
                this.ApellidoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular
        {
            get
            {
                return this.CelularField;
            }
            set
            {
                this.CelularField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia
        {
            get
            {
                return this.ContraseniaField;
            }
            set
            {
                this.ContraseniaField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail
        {
            get
            {
                return this.MailField;
            }
            set
            {
                this.MailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario
        {
            get
            {
                return this.NombreUsuarioField;
            }
            set
            {
                this.NombreUsuarioField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
}
namespace FacturanteModel
{
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Constantes.CodigoRespuesta", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteModel")]
    public enum ConstantesCodigoRespuesta : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SinDetalle = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ObjAutenticacionNull = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ObjItemsNull = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ObjClienteNull = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsuarioInvalido = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NroDocumentoNull = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DireccionFiscalNull = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RazonSocialNull = 7,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        PrefijoNull = 8,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoComprobanteNull = 9,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DetalleItemNull = 10,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        PVInvalido = 11,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoComprobanteInvalido = 12,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CondicionVentaInvalido = 13,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FechaAbonoInvalida = 14,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SinItems = 15,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SinCreditos = 16,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FechaComprobanteInvalida = 17,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        MontoTotalInvalido = 18,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        MontoNetoInvalido = 19,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoCambioInvalido = 20,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        MontoTotalItemInvalido = 21,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ComprobanteInvalido = 22,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SinEmails = 23,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorInterno = 500,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorInternoSinTalonario = 501,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Constantes.EstadoRespuesta", Namespace = "http://schemas.datacontract.org/2004/07/FacturanteModel")]
    public enum ConstantesEstadoRespuesta : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR = 2,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.facturante.com.API", ConfigurationName = "IComprobantes")]
public interface IComprobantes
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.facturante.com.API/IComprobantes/ListadoComprobantes", ReplyAction = "http://www.facturante.com.API/IComprobantes/ListadoComprobantesResponse")]
    FacturanteMVC.API.ListadoComprobantesResponse ListadoComprobantes(FacturanteMVC.API.ListadoComprobantesRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.facturante.com.API/IComprobantes/CrearComprobante", ReplyAction = "http://www.facturante.com.API/IComprobantes/CrearComprobanteResponse")]
    FacturanteMVC.API.CrearComprobanteResponse CrearComprobante(FacturanteMVC.API.CrearComprobanteRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.facturante.com.API/IComprobantes/CrearEmpresa", ReplyAction = "http://www.facturante.com.API/IComprobantes/CrearEmpresaResponse")]
    FacturanteMVC.API.CrearEmpresaResponse CrearEmpresa(FacturanteMVC.API.CrearEmpresaRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.facturante.com.API/IComprobantes/ReenviarComprobante", ReplyAction = "http://www.facturante.com.API/IComprobantes/ReenviarComprobanteResponse")]
    FacturanteMVC.API.ResponseBase ReenviarComprobante(FacturanteMVC.API.ReenviarComprobanteRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IComprobantesChannel : IComprobantes, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ComprobantesClient : System.ServiceModel.ClientBase<IComprobantes>, IComprobantes
{

    public ComprobantesClient()
    {
    }

    public ComprobantesClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public ComprobantesClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public ComprobantesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public ComprobantesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public FacturanteMVC.API.ListadoComprobantesResponse ListadoComprobantes(FacturanteMVC.API.ListadoComprobantesRequest request)
    {
        return base.Channel.ListadoComprobantes(request);
    }

    public FacturanteMVC.API.CrearComprobanteResponse CrearComprobante(FacturanteMVC.API.CrearComprobanteRequest request)
    {
        return base.Channel.CrearComprobante(request);
    }

    public FacturanteMVC.API.CrearEmpresaResponse CrearEmpresa(FacturanteMVC.API.CrearEmpresaRequest request)
    {
        return base.Channel.CrearEmpresa(request);
    }

    public FacturanteMVC.API.ResponseBase ReenviarComprobante(FacturanteMVC.API.ReenviarComprobanteRequest request)
    {
        return base.Channel.ReenviarComprobante(request);
    }
}
